.github/workflows/gradle-build.yml

The "slim" JARs are not runnable on their own so I think we shouldn't include them.

Only archive fat JARs

---

src/main/kotlin/models/glTF/Buffer.kt
src/main/kotlin/models/glTF/FloatVectorBuffer.kt
src/main/kotlin/models/glTF/MaterialBuffers.kt
src/main/kotlin/models/glTF/glTF.kt

I timed the export process
Before any changes, exporting 12850 at radius 8:
```
Took 29550330805 nanoseconds
Took 25447103456 nanoseconds
Took 20830986557 nanoseconds
Took 22491631446 nanoseconds
Took 20685962938 nanoseconds
```
Median 22.5 seconds / Mean 23.8 seconds
After first commit:
```
Took 16850471357 nanoseconds
Took 14769895850 nanoseconds
Took 13297833444 nanoseconds
Took 13833327370 nanoseconds
Took 13495152207 nanoseconds
```
Median 13.8 seconds / Mean 14.4 seconds
After second commit:
```
Took 3667631632 nanoseconds
Took 2749942353 nanoseconds
Took 3241219574 nanoseconds
Took 3616193326 nanoseconds
Took 2823936507 nanoseconds
```
Median 3.24 seconds / Mean 3.22 seconds
The above timings were taken with a fairly naïve approach of just calling `System.nanoTime()` like so:
```kt …
```

glTF export performance improvements

---

src/main/kotlin/cache/loaders/ModelLoader.kt
src/main/kotlin/cache/loaders/ObjectLoader.kt
src/main/kotlin/cache/loaders/SpriteLoader.kt
src/main/kotlin/cache/utils/ByteBufferExt.kt

Make ObjectLoader lazy (it takes about a half-second chunk of the initial load time for the objects to load). This means that they're instead loaded on-demand and will display warnings relevant to the selected region in the console rather than traversing all objects in the cache.
Additionally, reduce nullability and some other miscellaneous cleanups

Loader tweaks

---

CHANGELOG.md
src/main/kotlin/controllers/MainController.kt
src/main/kotlin/controllers/RegionChooserController.kt
src/main/kotlin/controllers/SettingsController.kt
src/main/kotlin/controllers/worldRenderer/Renderer.kt
src/main/kotlin/controllers/worldRenderer/SceneUploader.kt
src/main/kotlin/controllers/worldRenderer/WorldRendererController.kt
src/main/resources/theme.css
src/main/resources/views/main.fxml
src/main/resources/views/settings.fxml

**Current bug:**
If you set the FPS cap (to anything but 0) and then change it back to 0, it stays at the previous value.

Add setting for limiting the FPS

---

src/main/kotlin/cache/definitions/LocationsDefinition.kt
src/main/kotlin/cache/loaders/LocationsLoader.kt
src/main/kotlin/cache/loaders/RegionLoader.kt
src/main/kotlin/models/scene/SceneRegionBuilder.kt

Addresses #47 as much as we can from our end

Allow region loading even when xtea is missing (but warn)

---

src/main/kotlin/controllers/AboutController.kt
src/main/resources/views/about.fxml

Can't figure out how to get the description text in the middle to wrap:

Appearance improvements for About window

---

src/main/kotlin/ui/NumericTextField.kt

It so happens that in this LAF, "text" and "TextField.foreground" are the same, but apparently that is not always the case, so this is "more correct".

Use the correct UIManager key in NumericTextField

---

src/main/kotlin/controllers/LocationSearchController.kt
src/main/kotlin/controllers/RegionChooserController.kt

Makes it so that the first input is automatically focused when opening the "Change Region" or "Location Search" windows.

Automatically focus on the first input when opening windows

---

src/main/kotlin/cache/utils/Vec3F.kt
src/main/kotlin/models/scene/SceneRegionBuilder.kt

Has a few concessions to reintroduce some rounding errors present in the original code in order to not change the output
The goal here is deobfuscation rather than significant code change, and I think the goal of the function is a little clearer this way.

Make CalcTileColor a little less mysterious

---

src/main/kotlin/models/scene/SceneRegionBuilder.kt

- Mask the underlay ID with 0xff
- Fix a slightly broken coordinate wrapping function
Fix #66

Fix colour blending in wilderness

---

build.gradle.kts
run
run.bat

Turns out moving away from jogamp also lets us do this. Madness.

Allow `gradle run` (& simplify java params)

---

CHANGELOG.md
src/main/kotlin/models/glTF/Buffer.kt
src/main/kotlin/models/glTF/FloatVectorBuffer.kt
src/main/kotlin/models/glTF/MaterialBuffers.kt
src/main/kotlin/models/glTF/glTF.kt
src/main/kotlin/utils/ByteChunkBuffer.kt

Makes the initial area export consistently take ~~about 4-9% less time on my machine :^)~~ idk it goes faster, measurements are changing as I go
~~The difference for larger exports is a little more fine unfortunately~~

Small GLTF exporter optimisations

---

CHANGELOG.md
src/main/kotlin/controllers/worldRenderer/Renderer.kt
src/main/kotlin/controllers/worldRenderer/helpers/Animator.kt

This should reduce the perceived input lag/jitteriness and make the UI
more responsive while the FPS cap is turned on.

Move animator timing into another thread

---

CHANGELOG.md
src/main/kotlin/controllers/worldRenderer/Renderer.kt
src/main/kotlin/controllers/worldRenderer/SceneExporter.kt
src/main/kotlin/models/scene/Scene.kt
src/main/kotlin/models/scene/SceneRegion.kt
src/main/kotlin/models/scene/SceneTile.kt

This removes the x/y/z info from a SceneTile, since that's relative to
a scene and it's more expensive to update it in the tile than it is to
just pass it around.
The issue was ultimately caused by the x and y coordinates of a
SceneTile being mutable, and not being set at a time when they were
expected to be.
Fix #104

Fix chunk stacking when renderer is dead

---

src/main/kotlin/cache/definitions/ModelDefinition.kt

This hasn't ever caused a problem because the result of this specific
part of the concatenation is ultimately unused, but it's nice to have
the algorithm correct.

Remove some leftover code that makes model concat slightly incorrect

---

CHANGELOG.md
src/main/kotlin/controllers/worldRenderer/InputHandler.kt

3 is the default speed, and for every number you go up, it doubles the
speed. Holding shift quadruples your speed (as before) which is
equivalent to temporarily going 2 numbers higher.

Add keys to set fly speed (1-9)

---

CHANGELOG.md
src/main/kotlin/controllers/MainController.kt

This makes the process less likely to linger if the renderer doesn't
spawn.
As for why that only happens when the renderer doesn't spawn, I couldn't
say.

Stop animation timer on MainController dispose

---

CHANGELOG.md
src/main/kotlin/controllers/worldRenderer/Renderer.kt

Scale canvas to proper width/height even under high-DPI scaling

---

CHANGELOG.md
src/main/kotlin/cache/definitions/TextureDefinition.kt

The textures in the texture directory would brighten themselves every time they were exported. This means if you're up to your 5th export of the session, the textures will start looking noticeably washed-out.

Fix texture brightness changing between exports

---

src/main/kotlin/controllers/worldRenderer/GLSLPriorityRenderer.kt
src/main/kotlin/controllers/worldRenderer/Renderer.kt
src/main/resources/gpu/common.glsl
src/main/resources/gpu/comp.glsl
src/main/resources/gpu/comp_common.glsl
src/main/resources/gpu/uniforms.glsl
src/main/resources/gpu/vert.glsl

Like https://github.com/ConnorDY/OSRS-Environment-Exporter/pull/145 but doing away with them entirely since the version of GLSL we target doesn't necessarily always support them

Remove double-precision floats from shaders

---

run
run.bat

No changelog as this is a minor change
Still not sure how I would go about this in Windows, and WINE's batch support (especially with regexes in findstr) doesn't seem to be up to scratch.

Bump version to 2.4.1 in run scripts

---

CHANGELOG.md
README.md
src/main/kotlin/App.kt
src/main/kotlin/CliExporter.kt
src/main/kotlin/controllers/main/MainController.kt
src/main/kotlin/controllers/worldRenderer/SceneExporter.kt
src/main/kotlin/models/StartupOptions.kt
src/main/kotlin/models/config/ConfigOptions.kt
src/main/kotlin/models/config/types/ScaleMode.kt
src/main/kotlin/models/formats/GlTFExporter.kt
src/main/kotlin/models/formats/MaterialBuffers.kt

This lets the user choose whether they want 1:1 (Qodat-style), 1:100 (Old default), or 1:128 (default as of this PR, gives a 1 tile per unit export). It also allows this to be overridden on the command line via the `--scale` parameter.

Add configurable scale factor for export; default to 1:128

---

CHANGELOG.md
src/main/kotlin/App.kt
src/main/kotlin/CliExporter.kt
src/main/kotlin/controllers/main/MainController.kt
src/main/kotlin/models/DebugOptionsModel.kt
src/main/kotlin/models/StartupOptions.kt

Implementing #180, this allows the user to provide a list of Z layers to enable on the command line, e.g. `./run --z-layers 0,1`

Allow Z-layer selection on command line
