ConnorDY/OSRS-Environment-Exporter

CHANGELOG.md
src/main/kotlin/cache/loaders/RegionLoader.kt
src/main/kotlin/controllers/LocationSearchController.kt
src/main/kotlin/controllers/MainController.kt
src/main/kotlin/controllers/RegionChooserController.kt
src/main/kotlin/controllers/worldRenderer/Renderer.kt
src/main/kotlin/models/DebugModel.kt
src/main/kotlin/models/locations/Location.kt
src/main/kotlin/models/locations/Locations.kt
src/main/kotlin/utils/Utils.kt
src/main/resources/data/locations.json
src/main/resources/views/cache-chooser.fxml
src/main/resources/views/location-search.fxml
src/main/resources/views/main.fxml
src/main/resources/views/region-chooser.fxml

Implements #26.
Also made some small tweaks to the main window UI.

Add location search functionality

---

src/main/kotlin/cache/loaders/LocationsLoader.kt
src/main/kotlin/cache/utils/ByteBufferExt.kt

Not that it's an especially interesting place to be lol

Fix buffer underflow on loading region 11326

---

src/main/kotlin/cache/definitions/ModelDefinition.kt
src/main/kotlin/cache/definitions/converters/ObjectToModelConverter.kt
src/main/kotlin/cache/loaders/ModelLoader.kt
src/main/kotlin/controllers/worldRenderer/entities/Model.kt

Make Model{,Definition} less mutable and nullable

---

src/main/kotlin/controllers/worldRenderer/Renderer.kt
src/main/kotlin/controllers/worldRenderer/SceneExporter.kt
src/main/kotlin/controllers/worldRenderer/SceneUploader.kt
src/main/kotlin/controllers/worldRenderer/entities/Entity.kt
src/main/kotlin/controllers/worldRenderer/entities/Model.kt
src/main/kotlin/controllers/worldRenderer/entities/Renderable.kt
src/main/kotlin/controllers/worldRenderer/entities/StaticObject.kt
src/main/kotlin/controllers/worldRenderer/entities/TileModel.kt
src/main/kotlin/controllers/worldRenderer/entities/TilePaint.kt
src/main/kotlin/models/scene/SceneRegion.kt
src/main/kotlin/models/scene/SceneRegionBuilder.kt

Was going to lead into some related work around computeObj but that is for another day

Dead code removal & cleanup around computeObjs

---

CHANGELOG.md
src/main/kotlin/models/locations/Location.kt
src/main/resources/data/locations.json

Additional data came from here:
https://sheets.googleapis.com/v4/spreadsheets/1859HuKw5dXqmfakFd6e6kQ_PEXQA02namB4aNVQ0qpY/values/A:Z?key=AIzaSyBrYT0-aS9VpW2Aenm-pJ2UCUhih8cZ4g8

Update locations data with a more complete data set

---

src/main/kotlin/controllers/MainController.kt
src/main/kotlin/controllers/worldRenderer/Renderer.kt
src/main/kotlin/controllers/worldRenderer/entities/Model.kt
src/main/kotlin/controllers/worldRenderer/entities/TileModel.kt
src/main/kotlin/controllers/worldRenderer/entities/TilePaint.kt
src/main/kotlin/models/scene/Scene.kt
src/main/kotlin/models/scene/SceneRegion.kt
src/main/kotlin/models/scene/SceneRegionBuilder.kt
src/main/kotlin/utils/MathExt.kt

- Helps me understand what is going on
- Gives more accurate names to variables
- Removes some unused or misleading code
- Simplifies a few existing functions' logic/math

Refactor some colour/brightness-related code

---

CHANGELOG.md
build.gradle.kts
run
run.bat

Bump patch version for 2.0.2 release

---

src/main/kotlin/controllers/CacheChooserController.kt
src/main/kotlin/controllers/GridRegionChooserController.kt
src/main/kotlin/controllers/LocationSearchController.kt
src/main/kotlin/controllers/MainController.kt
src/main/kotlin/controllers/RegionChooserController.kt
src/main/kotlin/controllers/SettingsController.kt

This allows for easier navigation with alt+letter

Uppercase mnemonics and add where missing

---

CHANGELOG.md
src/main/kotlin/cache/definitions/ModelDefinition.kt
src/main/kotlin/controllers/worldRenderer/CPUNonPriorityRenderer.kt
src/main/kotlin/controllers/worldRenderer/entities/Entity.kt
src/main/kotlin/controllers/worldRenderer/entities/Model.kt
src/main/kotlin/controllers/worldRenderer/entities/Renderable.kt
src/main/kotlin/controllers/worldRenderer/entities/StaticObject.kt
src/main/kotlin/models/scene/SceneRegionBuilder.kt
src/main/resources/gpu/priority_render.glsl

Fix object rotations

---

src/main/kotlin/controllers/worldRenderer/helpers/Animator.kt

Fix a minor mistake in #97 where the FPS counter does not always update.
Not putting a changelog one in for this since it hasn't been officially released with that glitch

Fix FPS counter

---

src/main/kotlin/controllers/worldRenderer/helpers/Animator.kt
src/main/resources/gpu/frag.glsl

- Fix off-by-one dithering on some hardware (touches up on #102)
- Use semaphores for animator thread syncing (fixes a potential race condition introduced in #97)

Fix ordered dithering at full opacity on some hardware; fix potential race condition in Animator thread

---

src/main/kotlin/models/config/ConfigOptions.kt
src/main/kotlin/utils/Utils.kt

Hide priority render config option on macOS

---

build.gradle.kts
src/main/kotlin/controllers/worldRenderer/Renderer.kt

Addresses the underlying issue in https://github.com/ConnorDY/OSRS-Environment-Exporter/issues/104
Will need a few beta testers! Who knows what driver combinations could be lurking around the corner!

Use lwjglx-awt 0.1.9-SNAPSHOT version

---

src/main/kotlin/cache/definitions/ModelDefinition.kt
src/main/kotlin/cache/definitions/converters/ObjectToModelConverter.kt
src/main/kotlin/cache/loaders/LocationsLoader.kt
src/main/kotlin/cache/loaders/RegionLoader.kt
src/main/kotlin/controllers/worldRenderer/entities/Model.kt
src/main/kotlin/models/scene/SceneRegionBuilder.kt

Attempting to squeeze out a few optimisations around region loading. Didn't get an incredible amount, maybe 10% on a good day (measuring it is also hard).
So many ideas died here :(

Optimisations

---

CHANGELOG.md
src/main/kotlin/controllers/worldRenderer/InputHandler.kt

Don't make the camera jump around if the mouse can't be warped
Fix #123

Handle failed mouse warps

---

src/main/kotlin/controllers/main/SceneLoadProgressDialogSpawner.kt
src/main/kotlin/controllers/worldRenderer/Renderer.kt
src/main/kotlin/controllers/worldRenderer/SceneDrawListener.kt

Building on unreleased https://github.com/ConnorDY/OSRS-Environment-Exporter/pull/117

Show error in progress bar if drawing failed

---

.pre-commit-config.yaml

Run [`pre-commit install`](https://pre-commit.com/) in the repo to start using it

Automatic ktlintFormat via pre-commit

---

build.gradle.kts
src/main/kotlin/controllers/main/MainController.kt
src/main/kotlin/utils/PackageMetadata.kt

Convenience for `gradle run` usage

Fix gradle run version check

---

CHANGELOG.md
src/main/kotlin/controllers/worldRenderer/Camera.kt
src/main/kotlin/controllers/worldRenderer/GLSLPriorityRenderer.kt
src/main/kotlin/controllers/worldRenderer/InputHandler.kt
src/main/kotlin/controllers/worldRenderer/Renderer.kt
src/main/resources/gpu/common.glsl
src/main/resources/gpu/comp.glsl
src/main/resources/gpu/comp_common.glsl
src/main/resources/gpu/priority_render.glsl
src/main/resources/gpu/to_screen.glsl
src/main/resources/gpu/uniforms.glsl

The preview's camera:
- Jitters in power saving mode
- Tends to lock onto one axis when moving slowly
This should address those problems

Jittering camera fix for preview

---

CHANGELOG.md
src/main/resources/data/locations.json

Added location search data for Tombs of Amascut

Update locations.json with new Tombs of Amascut locations

---

CHANGELOG.md
README.md
package-release

Also updated the README with a few additions.

Include LICENSE, README.md, and CHANGELOG.md in packaged releases

---

src/main/kotlin/cache/definitions/ObjectDefinition.kt
src/main/kotlin/models/scene/SceneRegionBuilder.kt

Fixes https://github.com/ConnorDY/OSRS-Environment-Exporter/issues/81
Before:
After:

Add default object transform

---

src/main/kotlin/cache/loaders/LocationsLoader.kt

Fixes https://github.com/ConnorDY/OSRS-Environment-Exporter/issues/173 and https://github.com/ConnorDY/OSRS-Environment-Exporter/issues/172

Fix idOffset reading in LocationsLoader

---

build.gradle.kts
src/main/kotlin/cache/loaders/ObjectLoader.kt
src/main/kotlin/controllers/CacheChooserController.kt
src/main/kotlin/models/openrs2/OpenRs2Cache.kt
src/main/kotlin/models/openrs2/OpenRs2CacheKeys.kt
src/main/kotlin/utils/OpenRs2Api.kt

Attribute this PR to: https://github.com/ConnorDY/OSRS-Environment-Exporter/issues/196. It doesn't seem to fix the issue because the cache still doesn't fully load however, it will go out and get the correct `xteas.json` file from archive.openrs2.org if it cannot be found.

feat(xteas): Add auto-xtea cache key fetching from openrs2 archive API
